export const FETCH_CHANNELS = 'FETCH_CHANNELS',
  FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS',
  FETCH_CHANNELS_FAILURE = 'FETCH_CHANNELS_FAILURE',
  FETCH_USER_ACTIVITY = 'FETCH_USER_ACTIVITY',
  FETCH_USER_ACTIVITY_SUCCESS = 'FETCH_USER_ACTIVITY_SUCCESS',
  FETCH_USER_ACTIVITY_FAILURE = 'FETCH_USER_ACTIVITY_FAILURE';
